Squashed 'c_src/deps/asio/' changes from 66e76b9e4..bc87d093d
bc87d093d Re-enable building against LibreSSL
ffc9dd443 Implement fenced_block using std::atomic_thread_fence, when available.
595ff85c3 Add workaround for broken getaddrinfo in Apple's NAT64 environment.
bc6e494d2 Fix composed read/write operations when multiple buffers are supplied.
14db6371b Regenerate documentation.
b9d2d3ef0 Fix some long lines.
0fe8f4ded A smart pointer is not required to hold the work.
8737ab0f2 Update template parameter names in forward declaration to match implementation.
cb22512a9 Use string_view in basic_resolver and basic_resolver_entry.
6c97b611f Add tests for network_v* iostream output.
0090e946e Add string_view overloads for the make_network*() functions.
6503b3f33 Fix description of make_network_*() functions.
41cf38be8 Add string_view overloads for the make_address*() functions.
9c3c09ab6 Add string_view support to read_until and async_read_until.
0d7abb65f Add buffer() overloads for basic_string_view.
69a03d7b6 Rename DynamicBufferSequence to DynamicBuffer, is_dynamic_buffer_sequence to is_dynamic_buffer.
7b0a61e30 Defer assigning accepted socket until immediately before handler.
a2e070a79 Fix exception safety issue in hash_map.
b1b9e5c4a Add workaround for move-detection issue on MSVC 2015 Update 2.
2cde22623 Call SSL_COMP_free_compression_methods() on ssl cleanup.
41cb2faa1 Additional libraries required to link Boost.Coroutine.
af9770ac4 Use new TLS methods on OpenSSL 1.1.0.
7249bcc14 Backward compatibility for code using OpenSSL < 1.1.0.
503b8bb17 Fix allocator usage to compile with g++ 6.
6cec69ea0 Disable speculative operations after a short read or write.
c9e33cee0 New special concurrency hints.
6ef25d772 The null_event must sleep for correct behaviour of timed run functions.
79e3edd25 Allow use_future support to compile when exceptions are disabled.
85e011bb4 Update socket iostreams to adhere to the TS.
a48d0b4dd Add move support for deadline_timer.
be2458a44 Enable getaddrinfo by default on Apple platforms.
276846097 Fix dynamic buffer consume() implementation.
7268a3f48 Clean up header inclusion of old services.
26a0c8784 Strip out deprecated, extension and old services code.
348e4bd23 Mark basic_streambuf, regex, and match condition overloads as extensions.
14676ca0a Remove redundant deprecated preprocessor test.
d02c77e70 Fix mismatched preprocessor comment.
a8f9b3ced Fix MSVC Intellisense detection.
1aa65b56c Minimise overloads of buffer_size() and buffer_copy().
0a109643e Add socket_base::max_listen_connections, deprecate max_connections.
37d0d474f Remove SSL_accept locking for OpenSSL 1.0 and later.
a9fa5bf24 Add limited support for regular file descriptors.
0d78be17c Regenerate documentation.
ec50a1b96 Use stable index ids.
e8f545460 Make deleted copy constructor and assignment operator private.
6f86878ff Explicitly construct return type in the dynamic buffers' data() member functions.
69e44a4cc Fix errors when OPENSSL_NO_DEPRECATED is defined.
443bc17d1 Automatically handle glibc variant of strerror_r without #ifdefs.
0c262fe07 Only apply firewall workaround when getsockname outputs INADDR_ANY.
d636aafe8 Ensure new headers are self-contained.
a00d18464 Update const_buffer and mutable_buffer operator+ to strictly adhere to TS.
3909c65a1 Add operator+= to const_buffer and mutable_buffer.
c65f3bd16 Refactor the detail::consuming_buffers template.
062b19c97 Add compatibility with OpenSSL 1.1 - SSLv2 has been completely removed from OpenSSL, even without OPENSSL_NO_SSL2 - there is a new threading API without locking callbacks - struct SSL_CTX has been made opaque and must be used via accessor functions - some cleanup functions have been removed
0999ec96d Regenerate documentation.
87ecd843d Disable io_context::work when ASIO_NO_DEPRECATED is defined.
cbcaf259c Update requirements, overview and quick reference.
4d199b84d Add tsify.pl script.
24bdca206 Deprecate error_code returns on synchronous operations.
c1f2a3b73 Add ASIO_NO_EXTENSIONS to disable the non-TS parts of the API.
0f6478c9c Update copyright notices.
7b8815ea4 Make unit tests work when ASIO_NO_DEPRECATED is defined.
7ea623bbc Update asio/ts/* header files to match networking TS.
5316fbba3 Don't include deadline_timer headers when Boost.Date_Time is disabled.
16120e1bd New const/mutable buffer sequence requirements.
6176a69c8 Rename header to 'net' to match TS.
cacd7e9a8 Add timed run functions to the io_context.
8a380c97f Don't use deprecated functions in io_context unit test.
9f2f461ac Add io_context::count_type typedef.
c2077b2d8 Deprecate io_context run functions that have an error_code parameter.
4d37def63 Add forward declaration header as specified by TS.
826d26497 Fix typedefs for system_clock and steady_clock when std::chrono is used.
b39b750f4 Add support for service identification using the key_type typedef.
36302fc75 Make example executors shallow const.
a6b948a53 Ignore io_context unit test binary.
6c303a2ef Fix forwarding async operations in buffered streams.
5bebdf6e8 Update use_future interface and implementation.
62d26b670 Add two-parameter async_result specialisations for basic_yield_context.
7a46efd8b New async_result with two template parameters.
428ec47e4 Update list of installed headers.
f932359a4 Add socket() accessor to iostreams. Make basic_socket_streambuf::error() public.
9fb2d82fb Add move support for resolver objects.
a1f71f95c Make is_executor<> trait automatic.
3dd8a77af Remove the service template parameters, and the corresponding classes.
44f3ade70 Support for building with OpenSSL when OPENSSL_NO_SSL3 is defined.
722f7e2be Add std::bind examples to handler type requirements.
608a1789e Fix handling tracking to work with shallow-const executors.
de40487bc Add note about not destroying an SSL stream while there are pending operations.
726fb2768 Fix move constructor used by regex-based async_read_until.
5fa805398 BoringSSL does not provide CONF_modules_unload.
92bfc623e Add new error category and constant for ssl::error::stream_truncated.
e9fd1c972 Regenerate certificates for SSL example.
b79642e7c Use CreateEventW rather than CreateEvent.
7d8916137 Pass correct output buffer size to strncat.
eb22276c3 Binders need to use decay to work correctly with references.
d4f7d5cae Make executors shallow-const.
fe7dbb75f Suppress unused typedef warning when using clang.
6c70257e2 Use SSL_CTX_clear_chain_certs, if available.
522ce627c Add aliases for chrono facilities.
8fa67b79c Refactor detection of compiler thread support.
583e059ae Fix MSVC warning.
e2c60ab0b Enable noexcept for newer MSVCs.
1d32436b5 Add support for Windows 8.1 store apps.
5b89400ac Don't dereference the end iterator when async_connect exhausts the range.
34412f72d Use correct value for the basic_resolver_results::end() iterator.
81f7fbd8f Change type of concurrency_hint to int.
5f9639bc1 Mark buffer functions with noexcept.
70aecd80c Add data() and size() member functions to buffers.
24c6d7e3c Fix up some I/O objects to use non-deprecated get_executor().
f1ebd9522 Rename execution_context members to shutdown and destroy.
d3bbf3756 Don't provide io_service typedef when ASIO_NO_DEPRECATED is defined.
47b956f53 Regenerate documentation.
45124f33b Rename io_service to io_context.
b056bff78 Fix some long lines.
1eb5936c2 Rename executor_work to executor_work_guard.
ee382429e Rename address_v4's to_ulong() to to_uint() and add uint_type typedef.
66a8bbd68 Ifdef out deprecated address member functions.
20ca1e1d2 Rename wrap() to bind_executor().
c406fa7ce Remove address_cast.
15803ab00 Prevent multiple definition of ASIO_ERROR_CATEGORY_NOEXCEPT with newest MSVC.
fcf901ecb Update thread-private work count when epoll operations are not complete.
5ab5356e3 Disable old resolver functionality if ASIO_NO_DEPRECATED is defined.
69ff104a0 Code fixes so that the boostify script works.
74fe2b8e1 Deprecate resolver::query. Use overloads of resolve and async_resolve.
bc4eec8eb Use range-based interface for returning resolver results.
99c95166c Fix typo in comment.
cba39c6af Add allocator-aware accessors to ip::basic_resolver_entry.
9c8d15c6b Disable __thread keyword extension for android+x86+clang.
1d19a0060 Fixes for solaris.
5bb7a7419 Extend handler tracking to cover reactor-related events.
b2e85caeb Don't push/pop options around Boost.DateTime header.
e1c06ac35 Fix integer conversion warnings on 64-bit Windows.
aa21de094 Remove redundant pointer check in SSL engine.
4b07c86ec Fix race condition in windows::object_handle.
765918cd3 Use default visibility everywhere.
3c3e59576 Fix mismatched #endif comments.
88813bb3d Fix WinRT detection.
628e3ca9f ERR_remove_state is deprecated, use ERR_remove_thread_state instead.
8815161b2 Fix unit test code to work with boost::detail::atomic_count.
915d4cf6f Fix compile error in /dev/poll reactor.
9733ac676 Make all kqueue event registration lazy.
38051268e Deregister EVFILT_WRITE to avoid spinning with serial ports.
37e4e62c5 Use correct type in byte order conversion of shorts.
f7695e66a Fix shadow variable warnings.
b72b473cd Add lazy kqueue EVFILT_WRITE registration.
4b1731d97 New macro ASIO_DISABLE_CONNECTEX to disable ConnectEx use.
164b961f9 Remove dependency on Boost.Test.
23b084bb6 Fix up support for ASIO_NO_EXCEPTIONS.
df9d70bc5 Fix up support for ASIO_NO_TYPEID (i.e. no RTTI).
e19f2bd66 Strip the scope id from address string before passing to inet_pton.
6614ff63b Fix handler tracking on WinRT.
55194c01f Remove accidentally committed makefile change.
d4f7353a9 Track the underlying reactor operations associated with handlers.
f1de530de Pass native handle (e.g. descriptor) to handler tracking.
829b4c88d Add missing implementation header to src.hpp.
5d686abf9 Update handler tracking arguments.
27f8c672a Update reference index to use new address iterator/range names.
a35e2e012 Add basic_address_iterator and basic_address_range templates.
17efec180 Add use_future_::rebind() as replacement for operator[].
459917981 Finish implementation of move-enabled accept/async_accept.
c05c71e96 Revert "Change ip::address default constructor to be not-an-address."
f475b2143 Initial implementation of move-enable accept/async_accept.
7eee8f187 Add support for custom handler tracking.
7c9309717 Fix handler tracking for support for the new strand.
91b3bb1c7 remove_reference is not needed in async_completion constructor.

git-subtree-dir: c_src/deps/asio
git-subtree-split: bc87d093d1b9480b9960796496948fc3fed65b43